### PR TITLE
Update LSL to SL Server v16.12.03.322072

### LINKED ISSUE #10: Add changes from 16.05.24.315768
``` text
ATTACH_FACE_JAW, integer 47
ATTACH_FACE_LEAR, integer 48
ATTACH_FACE_LEYE, integer 50
ATTACH_FACE_REAR, integer 49
ATTACH_FACE_REYE, integer 51
ATTACH_FACE_TOUNGE, integer 52
ATTACH_GROIN, integer 53
ATTACH_HIND_LFOOT, integer 54
ATTACH_HIND_RFOOT, integer 55
ATTACH_LHAND_RING1, integer 41
ATTACH_LWING, integer 45
ATTACH_RHAND_RING1, integer 42
ATTACH_RWING, integer 46
ATTACH_TAIL_BASE, integer 43
ATTACH_TAIL_TIP, integer 44
```

### LINKED ISSUE #19: Update keywords with changes from Oct-Dec 2016
### Constants

- `PRIM_ALLOW_UNSIT (int) 39`
  - `[ PRIM_ALLOW_UNSIT, integer flag ]`
- `PRIM_SCRIPTED_SIT_ONLY (int) 40`
  - `[ PRIM_SCRIPTED_SIT_ONLY, integer flag ]`
- `PRIM_SIT_TARGET (int) 41`
  - `[ PRIM_SIT_TARGET, integer active, vector offset, rotation rot ]`

### Functions

- `integer llSitOnLink(key agent_id, integer link)`

| Error return constant | value | description |
| --- | --- | --- |
| `SIT_NOT_EXPERIENCE` | -1 | The script is not running as part of an experience with a valid experience key. |
| `SIT_NO_EXPERIENCE_PERMISSION` | -2 | The agent has not granted permission. |
| `SIT_NO_SIT_TARGET` | -3 | Unable to find an open sit target. |
| `SIT_INVALID_AGENT` | -4 | Unable to find specified agent. |
| `SIT_INVALID_LINK` | -5 | Unable to find specified link or the link constant would return multiple prims. |
| `SIT_NO_ACCESS` | -6 | The avatar does not have access to the parcel that the prim running this script is located in. |
| `SIT_INVALID_OBJECT` | -7 | This value is returned if the llSitOnLink is trying to force the user to sit on something that cannot be sat upon (such as an attachment). |

### Constants:

* `OBJECT_GROUP_TAG (int) 33`
* `OBJECT_TEMP_ATTACHED (int) 34`

### Constants:

* `OBJECT_ATTACHED_SLOTS_AVAILABLE (int) 35`

### PR DESCRIPTION
**Pull request by buildersbrewery**
---

* fixes #10
* fixes #19

---

Include changes from:

* [`16.10.07.320397`](http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/16#16.10.07.320397)
* [`16.11.02.321369`](http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/16#16.11.02.321369)
* [`16.12.03.322072`](http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/16#16.12.03.322072)

### CODE REVIEW

**Comment by dialupdisaster** [comment]
Hey @buildersbrewery I will get this into the plugin in the next few days. I wanted to see what you thought about me cleaning up the matches to be multiline so the changesets are cleaner when things are added or removed. 

Kind of like they do in the ruby language plugin https://github.com/atom/language-ruby/blob/master/grammars/ruby.cson#L108

That way its not just some big blob change when a method or something is added or removed.

**Comment by buildersbrewery** [comment]
@digitalfiz sounds good to me. 

* while you're at it, maybe you could sort the snippets of the regex to some extent? The order is slightly messed up, although it doesn't bother me too much, yet.
* and please keep the regexes readable, not like [`this generated one`](https://github.com/Makopo/sublime-text-lsl/blob/cd2cd168b4ca74b4122fb34f228fe864d0e5053e/lsl.tmLanguage#L356).
  * if you'd like to switch to a generated one for your project, see [`makopo/sublime-text-lsl`](https://github.com/makopo/sublime-text-lsl), [`makopo/kwdb_to_sublime`](https://github.com/makopo/kwdb_to_sublime) and [`bitbucket:Sei_Lisa/kwdb`](https://bitbucket.org/Sei_Lisa/kwdb)

**Comment by dialupdisaster** [comment]
Yeah I will probably error on the side of more ORs to keep some of the oogliness down. really another reason why I wanted to revamp the matches to make them ore readable on top of making the commits cleaner

**Comment by buildersbrewery** [comment]
@XenHat Could you update your lslint to the latest SL server version? Mentioning you here as your repo doesn't have an issue tracker 😆

**Comment by XenHat** [comment]
@buildersbrewery I assume you mean the binary?

**Comment by buildersbrewery** [comment]
@XenHat Yeah, kwdb has the latest changes to the grammar.

**Comment by buildersbrewery** [comment]
@XenHat If you'd like to test Windows builds as well via CI services, <https://www.appveyor.com/> has you covered. Compare <https://www.appveyor.com/docs/build-configuration/>. Travis won't do Windows afaik.

**Comment by XenHat** [comment]
I run windows builds myself, so that's not really an issue. Thanks for the tip though, much appreciated 👍

**Comment by buildersbrewery** [comment]
@XenHat I know, you could require appveyor CI builds to pass though for pull requests... Just for consistency's sake and to automate things. But maybe that's too much work for what it's worth.

**Comment by XenHat** [comment]
Binaries updated :)

**Comment by buildersbrewery** [comment]
@digitalfiz FYI: I updated the functions regex in buildersbrewery/linden-scripting-language@bf0ff29 (mainly sorted parts and condensed where appropriate). The new regex passes the Sublime syntax tests. Working on the integer constants one next.

**Comment by buildersbrewery** [comment]
@digitalfiz integer constants regex updated in buildersbrewery/linden-scripting-language@8f49683 and tested against Sublime syntax tests.

**Pull request merged**
